### ISSUE TITLE
Users can view empty credit batches they previously held.

### ISSUE THREAD

**Issue by S4mmyb** [regen-network/regen-web#1949] opened 2023-06-29 21:24 UTC
**Describe the bug**
In my user profile I can view credit batches I previously held, but no longer hold. 

**To Reproduce**

**Expected behavior**
Once I sell, or transfer a credit batch and no longer hold credits of that batch, they should disappear from the user profile. 

**Screenshots**
![image](https://github.com/regen-network/regen-web/assets/67330492/8c71d27f-41bd-4e80-b87a-28c7e2329dc4)

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment] 2023-07-04 08:58
This issue comes from the ledger originally which doesn't prune credit batches with empty balance: https://github.com/regen-network/regen-ledger/issues/1889 but such credit batches should be hidden already on the front-end, this was done as part of https://github.com/regen-network/regen-web/pull/1853
maybe some regression happened since then? cc/ @flagrede

**Comment by flagrede** [comment] 2023-07-06 12:32
They should be hidden indeed, it might be a regression or another case that is not handled.

**Comment by ryanchristo** [comment] 2023-07-27 16:31
Is this the same as what was resolved in #1979? Can we close this issue or is this something different?

**Closed** 2023-07-31 07:00 UTC
Labels: bug, dev
