### ISSUE TITLE
Error code 500 when adding a photo to 'Story Video or photo' in project profile

### ISSUE THREAD

**Issue by beccaRND** [regen-network/regen-web#2327] opened 2024-03-18 21:29 UTC
**Describe the bug**
I successfully added photos to the media section for an on chain project C06-001. In the Story Video or photo section I selected add photo, it allowed me to select a photo in the pop up box but when I hit add it gave me an error message and did not successfully save. I refreshed and tried again, same error. 

**To Reproduce**
 code 500 

**Expected behavior**
it should add the photo similar to sections above 

**Screenshots**
![Screenshot 2024-03-18 at 5 24 48 PM](https://github.com/regen-network/regen-web/assets/98425349/afa3c890-f459-4ace-8bc5-f29a8a2e9e10)

**Desktop (please complete the following information):**
 - OS: 
 - Browser:  chrome 
 - Version: 

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment] 2024-03-21 12:11
I've looked at the server logs and it looks like it's a duplicate of https://github.com/regen-network/regen-server/issues/449
this happens when we try to upload the same image several times.

**Closed by blushi** 2024-03-21 12:11 UTC
Labels: bug, dev
