### ISSUE TITLE
Roles page - cannot create new entitites

### ISSUE THREAD

**Issue by mhagel** [regen-network/regen-web#811] opened 2021-12-07 16:08 UTC
**Describe the bug**

**To Reproduce**
1. Go to https://deploy-preview-809--regen-registry.netlify.app/project-pages/edit/000d9e3a-4d5c-11ec-b0f2-0267c2be097b/roles (or with any project id)
2. Click on a role, click "Add Organization"
3. Fill out the form, click save
4. First problem: new organization should be selected in the input field
5. Click on the field
6. Second problem: white screen crash
7. Also, after reload, the new organization is not available to be selected
8. Also, there should be an Edit button visible for existing entities.

**Expected behavior**
- newly created entity should be selected in the input field
- newly created entity should be select-able in the role dropdown
- there should be an Edit button visible for existing entities

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment] 2022-04-22 13:41
@mhagel I'm wondering whether this is a duplicate of https://app.zenhub.com/workspaces/regen-registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-registry/703, it seems like it's describing the same issue, thoughts?

**Closed** 2022-06-30 10:55 UTC
Labels: bug, dev
