### ISSUE TITLE
Projects Missing on Credit Class Page

### ISSUE THREAD

**Issue by mhagel** [regen-network/regen-web#1364] opened 2022-10-05 05:17 UTC
**Describe the bug**

Project cards of projects registered under a credit class should be visible at the bottom of the credit class page - they currently aren’t 

**To Reproduce**
1. Go to https://redwood--regen-registry.netlify.app/credit-classes/C45

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

    

- Project page (pay attention to the "additonal info" section): https://www.figma.com/file/seUiQM2SPt78KJiDL0Ea8m/Basic-Ecocredits-Ledger-View-%2F-Marketplace?node-id=3495%3A166691

  

-   Credit class page (pay attention to this part of the page: https://monosnap.com/file/BHFp7j6OlGk3NNQ8abAtOGfkxQLn2n): https://www.figma.com/file/seUiQM2SPt78KJiDL0Ea8m/Basic-Ecocredits-Ledger-View-%2F-Marketplace?node-id=3495%3A161488

   

-  Credit batch page (just change the additional info section on the right side): https://www.figma.com/file/seUiQM2SPt78KJiDL0Ea8m/Basic-Ecocredits-Ledger-View-%2F-Marketplace?node-id=3513%3A165400

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by flagrede** [comment] 2022-10-05 08:52
This might be duplicate of regen-network/regen-registry#1266
/cc @victordelval

**Comment by victordelval** [comment] 2022-10-05 10:00
@mhagel @flagrede Indeed, task 1266 (or [PR 1339](https://github.com/regen-network/regen-web/pull/1339)) comes to solve this issue, along with the new cards prepared to buy ecocredits...

**Closed** 2022-10-05 10:00 UTC
Labels: bug, dev
