### ISSUE TITLE
"yarn start" command watches env file changes but reloader doesn't pick those up

### ISSUE THREAD

**Issue by wgwz** [regen-network/regen-web#2057] opened 2023-08-30 19:46 UTC
**Describe the bug**

**To Reproduce**
1. Have the app running with `yarn start`
2. Make a change to the marketplace env file, i.e. VITE_BLOCK_EXPLORER
3. Observe the reloader saying it picked up the change
4. Go to your browser and check "view transaction" in the activity table and see that your latest change is not picked up

**Expected behavior**

Env var changes and the reload should respect those changes.

**Additional context**

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by flagrede** [comment] 2023-09-14 13:06
I just tested and it does take into account after the restart.
This might be an environment-specific issue (I tested it on macOS).
We also recently bumped vite so it might have fixed this issue at the same time.
@wgwz Could you check if you're still having the issue ?

**Comment by flagrede** [comment] 2023-09-27 07:37
Putting that back into the tech backlog since it seems to be a Linux-specific issue so I can't really debug it.

**Comment by blushi** [comment] 2023-09-27 11:37
I can actually reproduce this on macOS

**Comment by flagrede** [comment] 2023-09-27 11:49
@blushi Could you try the following?
`rm -rf`  your node_modules  both in the root and marketplace folders, then run `yarn cache clean`  and then run 'yarn install` again. Let me know if it helps.`

**Comment by blushi** [comment] 2024-11-18 12:18
this is now working for me, I'll close this but keep it in mind in case it appears again

**Closed by blushi** 2024-11-18 12:18 UTC
Labels: bug, dev
