### ISSUE TITLE
Web2 Login/Profile testing

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-web#2248] opened 2023-12-11 16:49 UTC
This should be testing from https://dev.app.regen.network/
In the following, web2 account means account with a login and/or google email but no wallet address and web3 account means account with a wallet address.

### Log in:

- [ ] Log in with email:

    - From mobile or desktop
    - Enter email address and receive a passcode by email
    - Resend passcode after waiting 60sec, it should send a new passcode that would invalidate the first one
    - Enter wrong passcode, more than the max number of retries (3), it should error with "Too many attempts"
    - Wait until the passcode has expired (5 min) to enter it, it should error with "This code has expired!"
    - Enter correct passcode, it should log you in
    - Being logged in, it should display the email address in the top right user menu
    - Main login email should not be editable

- [ ] Log in with google

    - From mobile or desktop
    - Use an email not used by any account, it should create a new account and log you in
    - Use an email already used for logging in via email or google, it should log you in to the corresponding existing account
    - Being logged in, it should display the main account email address in the top right user menu (which could be different from the google email address, see #connect-login-providers section)
    - Main login email should not be editable

- [ ] Log in with Keplr

    - From desktop only
    - Use a wallet address not used by any account and prove ownership, it should create a new account and log you in
    - Use a wallet address already used  and prove ownership, it should log you in to the corresponding existing account
    - Being logged in, it should display the wallet address in the top right user menu
    - Main login email if not defined should be editable (see #connect-login-providers section)

- [ ] Log in with WC

    - From mobile or desktop
    - Use a wallet address not used by any account, it should simply connect this address but no account will be created, only on chain actions are enabled in this case (since `signArbitrary` used for proving wallet ownership and logging in to regen-server is not supported by Keplr WC client)
    - Use a wallet address already used by another account, it should simply connect this address but on the profile page, it should display the existing account information (for instance, if you had logged in via Keplr with it and edited your profile), although it's not editable in this case
    - Being connected, it should display the wallet address in the top right user menu

### Connect login providers

This feature provides multiple ways of logging in into a same account. This can be tested from https://dev.app.regen.network/profile/edit/settings while being logged in.

- [ ] Connect google
     - Log in to an account that is not yet connected to google (can be done via email or Keplr)
     - Connect google using a google email that is not already used as google email by another account, it should connect successfully to google.
     - Log out then log in via google using this google email, it should log you in to the same account
     - Disconnect from google
     - Connect google using a google email that is already used as google email by another account, it should throw a server error
       
       
- [ ] Connect wallet

     - Log in to an account that has not yet connected any wallet address (can be done via email or google)
     - Connect a wallet address not used by another account and prove ownership, it should connect successfully the wallet
     - Log out then log in via Keplr using this wallet address, it should log you in to the same account
     - Disconnecting wallet is not possible (yet)
     
- [ ] Connect login email

     - Log in to an account that has not yet connected any login email address (can only be done by a web3 account that has logged in through Keplr)
     - Connect an email address that is already used as login email by another account, it should error with "Sorry, this email is already connected to another account"
     - Connect an email address not used by another account, enter received code, it should connect successfully the email
     - Log out then log in via email using this email address, it should log you in to the same account
     - Once setup, the login email is not updatable (yet)
     

### Add and switch account

This feature behaves similarly to google accounts switcher but with the added complexity of maintaining the active account wallet address (if any) consistent with the account select in Keplr extension. The list of authenticated accounts are only persistent to the current session.

- Log in and click "+ add account" from the user dropdown to see the different methods for adding an account. This will automatically add the account to the current list of authenticated accounts.
- Switch to a web2 authenticated account by clicking on it in the account dropdown, it should simply switch to this account
- Switch from a web2 account to a web3 authenticated account: this should be possible as long as this account corresponds to the account address set in Keplr, else a warning is displayed.
- Log in with Keplr using wallet address A and switch to address B **from Keplr** which **is not part** of the authenticated accounts, you should be prompted to sign the arbitrary transaction. If this is successful, the account with address B will be added to the authenticated accounts and set as the active account.
- Log in with a Keplr wallet address A and switch to address B **from Keplr** which is already part of the authenticated accounts, it should simply update the active account to the account with address B.

### Perform on chain actions

 - [ ] from a web2 account:
 Log in using a web2 account and try to buy some ecocredits. On the "Choose how to purchase credits" modal, click "buy credits", it should suggest to connect a wallet to your account

 - [ ] From a web3 account that logged in via email/google and the wallet address selected in Keplr is different from the one of the current account: 
While being logged out, from Keplr extension, switch to a different wallet address (address B) than the account you're gonna get logged in with (address A). Log in via **email** to the web3 account with address A. Try to buy some ecocredits. It should display a warning modal to select the current account wallet address in Keplr in order to proceed. Switch to address A in Keplr. The warning modal should close and the buy action should resume.

### Create project

This feature allows to create project using any type of account (web2 or web3). This can be tested from https://dev.app.regen.network/profile/projects

- [ ] Account is a class issuer

A web3 account that is a class issuer can still create on chain projects but can also choose to create off chain projects without any credit class.

Log in via Keplr using an address that is a class issuer.

1. Create a new project with a credit class. Make sure the entire flow still works as before, in particular an on chain project is created at the end of the flow.
1. Edit a project with a credit class that is not on chain yet, it should go back to the step you left off in the project create flow
1. Edit an on chain project, behavior should be unchanged: on chain actions gets triggered when editing anchored data (basic info, location, roles and metadata)
1. Create a new project without any credit class:
   - no metadata form
   - the project shouldn't be created on chain but after final submission, it should be "published" meaning that if you go to the project page before this step, it will return 404 whereas if you go to the project page after the final review step submission, it will show the project data (use the UUID in the URL to go to the project page: https://deploy-preview-2178--regen-marketplace.netlify.app/project/{someUUID})

1. Edit a project without a credit class that hasn't been published, it should go back to the step you left off in the project create flow
1. Edit a project without any credit class that has been published:
   - no metadata form
   - you should be redirected to the project edit flow and editing shouldn't trigger any on chain actions (contrary to 3.)

- [ ] Account is not a class issuer

A web2 account or a web3 account that is not a class issuer can only create off chain projects without any credit class.

Log in with such an account and go through the steps 4, 5 and 6. The only difference should be that it won't show the "choose a credit class" page at the start of the project creation.

**Comment by erikalogie** [comment] 2024-01-09 19:19
TO DO- ping Cory to also QA

**Comment by blushi** [comment] 2024-01-10 12:13
@erikalogie @clevinson I added testing instructions. If you have any questions, feel free to ask.

**Comment by erikalogie** [comment] 2024-01-10 18:51
- The "create project" button is not responding to me. I have to refresh in order to see the "choose credit class" page. I'm using our shared testing account.

**Comment by erikalogie** [comment] 2024-01-11 15:48
@blushi 
- "Edit a project without any credit class that has been published: no metadata form. You should be redirected to the project edit flow and editing shouldn't trigger any on chain actions (contrary to 3.)" I am getting redirected to the project create form instead of the project edit form. See "Offchain project Jan 2024" in the shared testing account as an example.

**Comment by erikalogie** [comment] 2024-01-11 18:32
@blushi while testing the wallet connect stuff, I logged out and then tried to log back in with wallet connect and it is not working, see the video:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemE5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ab3aa22782708a08494534bd8f8e97ffddcf131/Screen%20Recording%202024-01-11%20at%202.28.12%20PM.mov)

**Comment by erikalogie** [comment] 2024-01-11 18:48
Wallet connect on mobile appears to be broken. I am getting the message on my mobile phone to scan the QR code instead of open the keplr app. <img width="363" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHk5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b01533a88a108f306609d633e896943369db38f/image.png" alt="image.png" />

**Comment by blushi** [comment] 2024-01-17 16:02
> > @blushi
> > 
> > * "Edit a project without any credit class that has been published: no metadata form. You should be redirected to the project edit flow and editing shouldn't trigger any on chain actions (contrary to 3.)" I am getting redirected to the project create form instead of the project edit form. See "Offchain project Jan 2024" in the shared testing account as an example.
> 
> I tested this and it does go to the edit form https://dev.app.regen.network/project-pages/ba1d299e-b097-11ee-8628-0267c2be097b/edit/basic-info but I'm suspecting some caching issue. Did that happen right after publishing the project (without you reloading the app in between)?

Ok I tested it myself and this is indeed what happens, I'll create a separate issue to fix this.

**Comment by blushi** [comment] 2024-01-22 09:49
> Also, I'm realizing that the warning for any wallet connect account that "Please switch to this address in Keplr to access this profile." doesn't make sense if they are trying to use wallet connect on desktop. This is a total edge case, but if they want to switch to a wallet connect account on desktop then they have to log out and log back in in order to do that.

I'm not sure how this would get triggered. Could you give precise steps to reproduce?

**Comment by erikalogie** [comment] 2024-01-22 12:58
> > Also, I'm realizing that the warning for any wallet connect account that "Please switch to this address in Keplr to access this profile." doesn't make sense if they are trying to use wallet connect on desktop. This is a total edge case, but if they want to switch to a wallet connect account on desktop then they have to log out and log back in in order to do that.
> 
> I'm not sure how this would get triggered. Could you give precise steps to reproduce? @erikalogie

@blushi so if you add a wallet connect address to your account dropdown, then switch to a different account, then try to switch back to the wallet connect account, there is no way to actually re-authorize with wallet connect because that is not an option. We could tackle this separately as it is an edge case.

**Comment by blushi** [comment] 2024-01-22 13:01
@blushi so if you add a wallet connect address to your account dropdown

This is not possible.
When adding an account, there's no Wallet Connect option.

<img width="617" alt="image" src="https://github.com/regen-network/regen-web/assets/3149358/c9520a16-6547-4288-bda8-3eb493f8460d">

**Comment by erikalogie** [comment] 2024-01-22 13:39
> This is not possible.
> When adding an account, there's no Wallet Connect option.

Ok weird. Maybe there was a bug before that allowed me to do this previously, but I can't reproduce it now. So no worries here.

**Comment by paul121** [comment] 2024-01-29 14:40
> Log in with WC

When I first click "Wallet Connect" I get a loading spinner that never completes. Closing the modal and clicking Login -> Wallet Connect again I get the QR code. This happens consistently on my 1st attempt after loading the webpage.

**Comment by blushi** [comment] 2024-01-30 10:22
> > Log in with WC
> 
> When I first click "Wallet Connect" I get a loading spinner that never completes. Closing the modal and clicking Login -> Wallet Connect again I get the QR code. This happens consistently on my 1st attempt after loading the webpage.

I can't reproduce this, which browser are you using?

**Comment by erikalogie** [comment] 2024-01-30 12:21
> > > Log in with Keplr using wallet address A and switch to address B from Keplr which is not part of the authenticated accounts, you should be prompted to sign the arbitrary transaction. If this is successful, the account with address B will be added to the authenticated accounts and set as the active account.
> > 
> > 
> > This works as described. But while it is convenient that an account is created for address B I wonder if this is always the desired behavior. It's not clear that the Keplr popup to sign an arbitrary transaction will auto-create an account. This caused an issue when I wanted to add address B to an existing web2 account (email) - but after switching the active Keplr wallet, the account got auto-created before I could add to my web2 account.
> 
> It would makes sense to add some kind of warning modal before displaying the Keplr popup when the user could decide to continue or not, thoughts @erikalogie? 

Would something like popup that we used to have work for this? https://www.figma.com/file/2ORMWGHMsB1rzGMrRIAtEV/Keplr-Log-In?type=design&node-id=972%3A41935&mode=design&t=nO4tweaR97x3gy0b-1

We need to warn him that no on chain action will be available until he switches back to the account address he's logged in with, this logic is already implemented:
> 
> <img alt="image" width="711" src="https://private-user-images.githubusercontent.com/3149358/300767308-ac88338b-4c3d-44b1-b126-1e1f93c94115.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTczMjIsIm5iZiI6MTcwNjYxNzAyMiwicGF0aCI6Ii8zMTQ5MzU4LzMwMDc2NzMwOC1hYzg4MzM4Yi00YzNkLTQ0YjEtYjEyNi0xZTFmOTNjOTQxMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzBUMTIxNzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDg5Y2UyMThjOTYzYzJkMmY0OWZhYzFmZTcyMjYzZWRhZGNmNDlkMWJhZDUyN2I1NmQ2YzUzNDJhNjE0ZjJkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QoYQkDgatwP9jakwzobnvzoMBQWg9fKGhxQs_YZ2Fdw">

**Comment by blushi** [comment] 2024-02-06 08:34
@paul121 I can reproduce the WC issue now, created an issue to fix that #2275, thanks for testing!

**Comment by clevinson** [comment] 2024-02-07 02:31
Issues I came across as I spent time testing today:

# Managing a Custom Profile

After logging in with email, I went to create a custom profile, and ran into few errors:
- [ ] Adding images (either avatar or header image) does not show the "Save" button, it is hidden in the overflow in modal, so this is confusing to users who may not know that they can scroll in the modal.

<img width="300" alt="Screenshot 2024-02-06 at 6 05 43 PM" src="https://github.com/regen-network/regen-web/assets/832188/b2ec977e-00a3-49c6-b1b9-e0c1748be8f6">
<img width="300" alt="Screenshot 2024-02-06 at 6 05 48 PM" src="https://github.com/regen-network/regen-web/assets/832188/1b1ea011-fdfc-46c0-b1a0-bd10ceb9dfb1">

- [ ] After editing the profile, clicking "View Profile" sends me to https://dev.app.regen.network/connect-wallet, which says "You must connect to Keplr in order to view the content of this page." instead of directing me to the profile page

<img width="500" alt="Screenshot 2024-02-06 at 6 06 58 PM" src="https://github.com/regen-network/regen-web/assets/832188/e6f7eca6-7040-4b08-a243-7dc52ab0864e">


# Project Creation Flow

- [ ] When editing the project page, I got confused between the Arrow keys and the "Save & Next" button. "Save & Next" was disabled / grey since I hadn't selected project size, and so I just filled out the form hitting the arrow keys. No data got saved. And then when I reached the final page, I had a green "Save & Next" button, but clicking on the button did nothing.
<img width="500" alt="Screenshot 2024-02-06 at 6 17 00 PM" src="https://github.com/regen-network/regen-web/assets/832188/9a93b42e-3a23-45e4-87b3-1d7b76408ecd">

**Comment by blushi** [comment] 2024-02-07 06:49
Thanks for testing @clevinson 

>  Adding images (either avatar or header image) does not show the "Save" button, it is hidden in the overflow in modal, so this is confusing to users who may not know that they can scroll in the modal.

We could simply have less vertical margin around this modal, wdyt @erikalogie?

> After editing the profile, clicking "View Profile" sends me to https://dev.app.regen.network/connect-wallet, which says "You must connect to Keplr in order to view the content of this page." instead of directing me to the profile page

I'll try to reproduce and investigate.

 When editing the project page, I got confused between the Arrow keys and the "Save & Next" button. "Save & Next" was disabled / grey since I hadn't selected project size, and so I just filled out the form hitting the arrow keys. No data got saved. And then when I reached the final page, I had a green "Save & Next" button, but clicking on the button did nothing. 

Any thoughts @erikalogie? Maybe we could add a warning saying the arrow keys are just for navigating the form, without saving the data. I think this was originally designed for the project plan creation form where you had quite long forms and this could have been useful to move on to the next form while you gather the info for the current one. But I'm not sure if that's so much useful here. Maybe we should just have some prev button and "save and next".

**Comment by blushi** [comment] 2024-02-07 07:38
> > > > Log in with Keplr using wallet address A and switch to address B from Keplr which is not part of the authenticated accounts, you should be prompted to sign the arbitrary transaction. If this is successful, the account with address B will be added to the authenticated accounts and set as the active account.
> > > 
> > > 
> > > This works as described. But while it is convenient that an account is created for address B I wonder if this is always the desired behavior. It's not clear that the Keplr popup to sign an arbitrary transaction will auto-create an account. This caused an issue when I wanted to add address B to an existing web2 account (email) - but after switching the active Keplr wallet, the account got auto-created before I could add to my web2 account.
> > 
> > 
> > It would makes sense to add some kind of warning modal before displaying the Keplr popup when the user could decide to continue or not, thoughts @erikalogie?
> 
> Would something like popup that we used to have work for this? https://www.figma.com/file/2ORMWGHMsB1rzGMrRIAtEV/Keplr-Log-In?type=design&node-id=972%3A41935&mode=design&t=nO4tweaR97x3gy0b-1

I'll create a task for that, we can have this done after the release since it's nice to have.

**Comment by blushi** [comment] 2024-02-07 08:15
> > After editing the profile, clicking "View Profile" sends me to https://dev.app.regen.network/connect-wallet, which says "You must connect to Keplr in order to view the content of this page." instead of directing me to the profile page
> 
> I'll try to reproduce and investigate.

@clevinson Good catch, I've got a fix here: https://github.com/regen-network/regen-web/pull/2280

**Comment by clevinson** [comment] 2024-02-08 00:33
> We could simply have less vertical margin around this modal, wdyt @erikalogie?

In general I would be in favor of us never having scrollable modals. I understand there may be exceptions to the rule sometimes, but its usually very unintuitive and feels like more of a UI bug then design. I also noticed that the login modal, it is in fact a scrollable div.
<img width="300" alt="Screenshot 2024-02-07 at 4 27 35 PM" src="https://github.com/regen-network/regen-web/assets/832188/75810859-d8c3-469d-b1f0-1d179334164c">
<img width="300" alt="Screenshot 2024-02-07 at 4 27 32 PM" src="https://github.com/regen-network/regen-web/assets/832188/3e6f8860-9033-4bdc-b7c6-bef2ac0c0449">

**Comment by clevinson** [comment] 2024-02-08 05:10
I sat down with Dave today and went over this flow. We probably have a few other items that we may want to tackle before marketing this feature (either publicly, or socializing it with partners via a soft launch). I'll work on getting more clarity on that list with him and @erikalogie soon, so we can discuss w/ the dev team next week about prioritizing it against other tasks.

Regardless tho, I wouldn't consider the issues that Dave and I are tracking as blocking closing this issue or a release from dev to main, if the rest of the team feels that the core technical bugs have been sufficiently resolved.

**Closed** 2024-03-04 16:08 UTC
