### ISSUE TITLE
Drop down on Credit Batch Issuance Page does not work 

### ISSUE THREAD

**Issue by beccaRND** [regen-network/regen-web#2300] opened 2024-02-27 19:28 UTC
**Describe the bug**
Once on the create credit batch page the dropdown for selecting a project does not work, no projects populate. The address that I am logged in as is regen1m2nyyufulc0uja2jawzvd0rar28vyp92r7pg6l. Cory added me as issuer to C57 credit class on Redwood so I should have permissions to create batches on any projects in this credit class. https://dev.app.regen.network/ecocredits/create-batch

**Expected behavior**
Select from projects in dropdown 

**Screenshots**

![Screenshot 2024-02-27 at 2 22 59 PM](https://github.com/regen-network/regen-web/assets/98425349/2494a830-28af-4fec-83a6-e390c56d2f8e)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome 
 - Version: latest 

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by clevinson** [comment] 2024-02-27 19:58
I think I have a decent idea of what the issue is here, as this is something I've faced in the past too.

My hypothesis is that we're not paginating successfully through the different projects to see all the issuers of all projects.  There are a lot of projects on devnet from the days when we were testing the bridge functionality.  I manage an address that is an issuer of many of these projects.  When I go to this batch page and I click on the project dropdown, it does not work for the first 30 seconds (during which I think it is waiting for the ledger queries).  Then eventually the dropdown populates but it populates with exactly 100 projects (C47-001..C47-100).  This address that I'm logged in to is an issuer of many other projects but they don't appear at all in the dropdown bc the dropdown is only getting results from these first 100 projects I think?

Either way, when I create a new keplr wallet and give that wallet issuer permissions, I get the exact same issuer as @beccaRND where the dropdown never populates.

**Comment by blushi** [comment] 2024-02-28 07:21
Yeah @clevinson I believe that's the issue indeed and we already have a separate issue to fix that: https://github.com/regen-network/regen-web/issues/2201 so I'll close this one.

**Closed by blushi** 2024-02-28 07:21 UTC
Labels: bug, dev
